import { useRef, useState } from 'react';
import { ChevronDown, Ruler, RotateCcw, X } from 'lucide-react';
import { loadOpenCv, stableEstimate, validateReference, type EstimateResult, type Point } from '../lib/estimate';
import { STEPS, type Photos } from '../lib/photos';
const labels=['Top-left corner','Top-right corner','Bottom-right corner','Bottom-left corner','Start of distance (A)','End of distance (B)'];
export function OptionalEstimate({photos,result,onResult}:{photos:Photos;result:EstimateResult|null;onResult:(r:EstimateResult|null)=>void}) {
  const [open,setOpen]=useState(false);const [photoId,setPhotoId]=useState('wall');const [model,setModel]=useState('');const [width,setWidth]=useState('');const [height,setHeight]=useState('');const [unit,setUnit]=useState<'in'|'cm'>('in');
  const [clear,setClear]=useState(false);const [plane,setPlane]=useState(false);const [points,setPoints]=useState<Point[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [correction,setCorrection]=useState('');const img=useRef<HTMLImageElement>(null);const revision=useRef(0);
  const photo=photos[photoId as keyof Photos];
  function invalidate(){revision.current++;onResult(null);setError('');setCorrection('');setBusy(false);}
  function resetPhoto(id:string){invalidate();setPhotoId(id);setPoints([]);setClear(false);setPlane(false);}
  async function estimate(){
    invalidate();const token=revision.current;
    if(!photo||!clear||!plane){setError('Can’t estimate reliably—Base team review needed. Confirm a clear, straight-on view and a shared flat wall plane.');return;}
    const reason=validateReference(points,Number(width),Number(height));
    if(reason){setError(`Can’t estimate reliably—Base team review needed. ${reason}`);return;}
    setBusy(true);
    try{const cv=await loadOpenCv();if(token!==revision.current)return;const value=stableEstimate(cv,points,Number(width),Number(height));onResult({distance:value,unit,model,corrected:false,sample:photo.source==='sample'});}
    catch(e){if(token===revision.current)setError(`Can’t estimate reliably—Base team review needed. ${e instanceof Error?e.message:''}`);}
    finally{if(token===revision.current)setBusy(false);}
  }
  return <section className="optional-card"><button className="accordion-trigger" aria-expanded={open} onClick={()=>setOpen(!open)}><span className="optional-icon"><Ruler size={21}/></span><span><strong>Try approximate measurement</strong><small>Optional · separate from your photo checklist</small></span><ChevronDown className={open?'rotated':''} size={19}/></button>{open&&<div className="estimate-content"><p>A photo can only suggest a distance on one flat plane. This cannot estimate depth, verify electrical clearances, or approve a location.</p><div className="estimate-fields"><label>Meter model (optional)<input value={model} placeholder="Enter your model" onChange={e=>{invalidate();setModel(e.target.value);}}/></label><label>Photo<select value={photoId} onChange={e=>resetPhoto(e.target.value)}>{STEPS.map(s=><option key={s.id} value={s.id} disabled={!photos[s.id]}>{s.title}{!photos[s.id]?' — no photo':''}</option>)}</select></label></div><p className="field-help">Enter verified dimensions of the exact rectangular meter housing or reference face. We don’t look up model sizes. Do not use the bounding box of a round meter.</p><div className="dimension-fields"><label>Known width<input inputMode="decimal" type="number" min="0" step="any" value={width} onChange={e=>{invalidate();setWidth(e.target.value);}}/></label><label>Known height<input inputMode="decimal" type="number" min="0" step="any" value={height} onChange={e=>{invalidate();setHeight(e.target.value);}}/></label><label>Units<select value={unit} onChange={e=>{invalidate();setUnit(e.target.value as 'in'|'cm');}}><option value="in">Inches</option><option value="cm">Centimeters</option></select></label></div><label className="check-label"><input type="checkbox" checked={clear} onChange={e=>{invalidate();setClear(e.target.checked);}}/><span>The photo is straight-on and all four rectangular reference corners are clear.</span></label><label className="check-label"><input type="checkbox" checked={plane} onChange={e=>{invalidate();setPlane(e.target.checked);}}/><span>The reference face and both measurement points are on the same flat wall plane. A meter face projecting from the wall does <strong>not</strong> qualify.</span></label>
      {photo?<><div className="point-toolbar"><strong>{points.length<6?`${points.length+1}. Mark ${labels[points.length].toLowerCase()}`:'All points marked'}</strong><button className="text-button" onClick={()=>{invalidate();setPoints([]);}}><RotateCcw size={14}/> Reset points</button></div><div className="measurement-image" onClick={e=>{if(points.length>=6||!img.current)return;const bounds=img.current.getBoundingClientRect();const x=(e.clientX-bounds.left)/bounds.width*img.current.naturalWidth,y=(e.clientY-bounds.top)/bounds.height*img.current.naturalHeight;if(x<0||y<0||x>img.current.naturalWidth||y>img.current.naturalHeight)return;invalidate();setPoints([...points,{x,y}]);}}><img ref={img} src={photo.url} alt="Selected photo for marking reference corners and distance endpoints"/>{points.map((p,i)=><span key={i} className="measure-point" style={{left:`${p.x/(img.current?.naturalWidth||1)*100}%`,top:`${p.y/(img.current?.naturalHeight||1)*100}%`}}>{i<4?i+1:i===4?'A':'B'}</span>)}</div><p className="field-help">Tap the image in order: top-left, top-right, bottom-right, bottom-left, then the two ends of the distance. Or enter pixel positions below.</p><details className="coordinate-details"><summary>Enter or correct points with your keyboard</summary>{labels.map((label,i)=><div className="coordinate-row" key={label}><span>{label}</span>{(['x','y'] as const).map(axis=><label key={axis}>{axis.toUpperCase()}<input type="number" min="0" step="1" aria-label={`${label} ${axis}`} value={points[i]?.[axis]??''} onChange={e=>{invalidate();const next=Array.from({length:Math.max(i+1,points.length)},(_,index)=>points[index]??{x:0,y:0});next[i]={...next[i],[axis]:Math.max(0,Math.min(Number(e.target.value),axis==='x'?(img.current?.naturalWidth||0):(img.current?.naturalHeight||0)))};setPoints(next);}}/></label>)}</div>)}</details></>:<div className="inline-message">Add a photo to the checklist first, then select it here.</div>}
      <div className="estimate-actions"><button className="button primary" disabled={busy} onClick={()=>void estimate()}><Ruler size={17}/>{busy?'Estimating…':'Estimate distance'}</button><button className="text-button" onClick={()=>{invalidate();setOpen(false);}}><X size={15}/> Skip measurement</button></div><div role="status" aria-live="polite">{error&&<p className="estimate-error">{error}</p>}{result&&<div className="estimate-result"><span className="eyebrow">APPROXIMATE PHOTO ESTIMATE</span><strong>{result.distance.toFixed(1)} {result.unit}</strong><p>{result.sample?'Sample photo · ':''}{result.corrected?'Manually corrected · ':''}Same-plane distance only. Base team review needed.</p><div className="manual-correction"><label>Manual correction ({unit})<input type="number" step="any" min="0" value={correction} onChange={e=>setCorrection(e.target.value)}/></label><button className="button" disabled={!Number.isFinite(Number(correction))||Number(correction)<=0} onClick={()=>onResult({...result,distance:Number(correction),corrected:true})}>Apply correction</button></div></div>}</div></div>}</section>;
}
