import { ArrowLeft, ArrowRight, Camera, Check, CheckCircle2, CircleAlert, FileCheck2, Leaf, LockKeyhole, Pencil, RotateCcw } from 'lucide-react';
import { planWall, skippable } from '../lib/wall/survey';
import { completion, requiredSteps, type Answer, type Notes, type PhotoId, type Photos } from '../lib/photos';
import type { EstimateResult } from '../lib/estimate';
import { OptionalEstimate } from './OptionalEstimate';
const obstructions=['Nearby gas meter','AC unit','Window','Door','Vent','Wood pile','Bush','Other'];
type Props={photos:Photos;fence:Answer;location:string;notes:Notes;estimate:EstimateResult|null;finished:boolean;onNotes:(n:Notes)=>void;onFence:(a:Answer)=>void;onLocation:(v:string)=>void;onEstimate:(e:EstimateResult|null)=>void;onRetake:(id:PhotoId)=>void;onMark:(id:PhotoId,status:'confirmed'|'retake')=>void;onFinish:()=>void;onEdit:()=>void;onBack:()=>void};
export function Review(p:Props){
  const tally=completion(p.photos,p.fence,p.location);const skip=skippable(p.photos) as PhotoId[];const plan=planWall(p.photos);const steps=requiredSteps(p.fence);const samples=steps.filter(s=>p.photos[s.id]?.source==='sample').length;
  return <section className="review-page"><div className="capture-topbar"><button className="text-button" onClick={p.onBack}><ArrowLeft size={16}/> Back to photos</button><span className="small-private"><LockKeyhole size={13}/> Nothing is uploaded</span></div><div className={`review-heading ${p.finished?'finished-heading':''}`}>{p.finished&&<span className={`result-icon ${tally.ready?'':'incomplete'}`}>{tally.ready?<CheckCircle2 size={32}/>:<Camera size={32}/>}</span>}<div className="eyebrow">{p.finished?'YOUR PHOTO CHECK':'ONE LAST LOOK'}</div><h1>{p.finished?(tally.ready?'Ready for Base team review.':'A few more photos would help.'):'Looking good. Let’s review.'}</h1><p>{p.finished?'This pre-screen does not determine eligibility or approve an installation. Base’s team confirms site fit and requirements.':'Take a moment to check each photo. Clear details help the Base team understand your space.'}</p>{samples>0&&<div className="sample-banner"><CircleAlert size={17}/>{samples} {samples===1?'photo is a demo sample':'photos are demo samples'}. These don’t document your home.</div>}{p.finished&&<p className="local-result-note">Demo summary only. These photos have not been sent to Base. Keep this page open to keep your session.</p>}</div>
    {plan.summary&&<p className="space-summary"><FileCheck2 size={16}/> {plan.summary}</p>}<div className="review-count"><h2>Your photos</h2><span><b>{tally.complete} of {tally.total}</b> complete</span></div><div className="review-grid">{steps.map((s,i)=>{const photo=p.photos[s.id];return <article className="review-photo" key={s.id}><div className="review-thumbnail">{photo?<img src={photo.url} alt={`${s.title}${photo.source==='sample'?' — Base guide sample':''}`}/>:<Camera size={30}/>}<span className="thumbnail-index">{String(i+1).padStart(2,'0')}</span>{photo?.source==='sample'&&<span className="sample-label">SAMPLE</span>}<button className="thumbnail-retake" aria-label={`${photo?'Retake':'Add'} ${s.title}`} onClick={()=>p.onRetake(s.id)}>{photo?<RotateCcw size={15}/>:<Camera size={15}/>}</button></div><div className="review-photo-info"><h3>{s.title}</h3><span className={`photo-status ${photo?.status==='confirmed'||(!photo&&skip.includes(s.id))?'good':'needs-photo'}`}>{photo?.status==='confirmed'||(!photo&&skip.includes(s.id))?<Check size={13}/>:<CircleAlert size={13}/>} {!photo?(skip.includes(s.id)?`Not needed · ${plan.notNeeded[s.id as 'left'|'right'|'adjacent']?.toLowerCase()}`:'Missing'):photo.status==='retake'?'Retake suggested':photo.check?(photo.check.accepted?(photo.check.meterNumber?`Accepted · meter ${photo.check.meterNumber}`:photo.check.amps?`Accepted · reads ${photo.check.amps} A`:photo.check.limitedSpace?'Accepted · limited space noted':'Accepted · checked on device'):'Sent for Base team review'):'Complete · manually checked'}</span>{photo&&<div className="review-photo-actions"><button onClick={()=>p.onMark(s.id,'confirmed')} className={photo.status==='confirmed'?'selected':''}>I can read this</button><button onClick={()=>p.onMark(s.id,'retake')}>Flag for retake</button></div>}</div></article>})}</div>
    <div className="review-details"><section className="site-notes"><div className="card-heading"><span className="optional-icon"><Leaf size={21}/></span><div><h2>A little more about your home</h2><p>Homeowner observations · not verified by Base</p></div></div><fieldset><legend>Does a fence run along the meter wall?</legend><div className="segment-group">{(['yes','no','unsure'] as const).map(v=><button key={v} aria-pressed={p.fence===v} onClick={()=>p.onFence(v)}>{v==='unsure'?'Not sure':v==='yes'?'Yes':'No'}</button>)}</div>{(p.fence===null||p.fence==='unsure')&&<p className="field-help">Confirm this when you can. Base can help if you’re not sure.</p>}</fieldset><label className="review-location">Main breaker location<select value={p.location} onChange={e=>p.onLocation(e.target.value)}><option value="">Choose a location</option><option value="outside">Outside</option><option value="garage">Garage</option><option value="closet">Closet</option><option value="not sure">Not sure</option></select></label><fieldset><legend>Does your home have solar panels? <span>Optional</span></legend><div className="segment-group">{(['yes','no','unsure'] as const).map(v=><button key={v} aria-pressed={p.notes.solar===v} onClick={()=>p.onNotes({...p.notes,solar:v})}>{v==='unsure'?'Not sure':v==='yes'?'Yes':'No'}</button>)}</div></fieldset><fieldset><legend>What’s near the meter? <span>Optional</span></legend><div className="obstruction-chips">{obstructions.map(o=><label key={o}><input type="checkbox" checked={p.notes.obstructions.includes(o)} onChange={e=>p.onNotes({...p.notes,obstructions:e.target.checked?[...p.notes.obstructions,o]:p.notes.obstructions.filter(v=>v!==o)})}/><span>{o}</span></label>)}</div></fieldset><label className="notes-label">Anything else we should know? <span>Optional</span><textarea maxLength={1500} rows={3} value={p.notes.text} onChange={e=>p.onNotes({...p.notes,text:e.target.value})} placeholder="Access details, something you couldn’t safely photograph…"/></label></section><OptionalEstimate key={Object.values(p.photos).map(photo=>photo?.url).join('|')} photos={p.photos} result={p.estimate} onResult={p.onEstimate}/></div>
    {p.finished&&<div className="session-summary"><h2>Your observations</h2><p><strong>Fence:</strong> {p.fence??'Not answered'} <span>·</span> <strong>Solar:</strong> {p.notes.solar??'Not answered'} <span>·</span> <strong>Breaker:</strong> {p.location||'Not answered'}</p><p><strong>Nearby:</strong> {p.notes.obstructions.join(', ')||'No observations selected'}</p>{p.notes.text&&<p className="note-summary">{p.notes.text}</p>}{p.estimate&&<p><strong>Approximate photo estimate:</strong> {p.estimate.distance.toFixed(1)} {p.estimate.unit}{p.estimate.corrected?' · manually corrected':''}{p.estimate.sample?' · sample photo':''}. Separate from the photo checklist; Base team review needed.</p>}</div>}
    <div className="review-finish"><div><FileCheck2 size={20}/><p>{p.finished?'Your session stays here, on this device.':'Photos help Base review your home. They don’t approve an installation.'}</p></div><button className="button primary" onClick={p.finished?p.onEdit:p.onFinish}>{p.finished?<><Pencil size={17}/> Keep editing</>:<>Finish photo check <ArrowRight size={18}/></>}</button></div>
  </section>;
}
